INSERT INTO users (username, password, role, created_at, created_by, updated_at, updated_by) VALUES ("root@root.com", "$2a$10$EjqeWC7W.XyCAAa/mUMxFu0i.SgeX9nZThlGDx/M1WFXBSNmOfIpO", "ADM", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");

-- Lista de Bairros de Macapá com utc_timestamp
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Abacate da Pedreira", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Açaí", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Alvorada", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Amazonas", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Ambé", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Aparecida", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Arquipélago", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Bairro das Palmeiras", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Beirol", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Bioparque", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Boné Azul", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Brasil Novo", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Buritizal", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Cabralzinho", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Cantá", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Central", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Chefe Clodoaldo", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Cidade Nova", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Congós", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Coração", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Curiaú", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Fazendinha", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Goiabal", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Igarapé da Fortaleza", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Ilha de Santana", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Ilha Mirim", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Infraero", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Ipanema", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Jardim de Deus", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Jardim Eco-Lógico", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Jardim Felicidade I", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Jardim Felicidade II", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Jardim Marco Zero", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Jesus de Nazaré", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Km 9", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Laguinho", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Loteamento São José", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Macapaba", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Marabaixo I", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Marabaixo II", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Marabaixo III", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Marabaixo IV", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Morada das Palmeiras", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Muca", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Murici", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Nova Esperança", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Novo Buritizal", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Novo Horizonte", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Pacoval", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Palmares", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Pantanal", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Parque dos Buritis", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Pedrinhas", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Perpétuo Socorro", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Picuia", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Planalto", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Porto do Céu", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Renascer", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Ribeirão", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Santa Inês", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Santa Rita", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Santo Antônio", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("São Benedito", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("São José", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("São Lázaro", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Sol Nascente", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Trem", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Universidade", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Vila das Oliveiras", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Vila Igarapé", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Vila Maranhense", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Vila Operária", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Vila Progresso", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");
INSERT INTO districts (name, created_at, created_by, updated_at, updated_by) VALUES ("Zerão", utc_timestamp, "root@root.com", utc_timestamp, "root@root.com");